services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ai_models:/var/ai_models
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:0.3.11
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama:
  ai_models: